// <auto-generated />
namespace WadGraphEs.MetricsEndpoint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addazuresubscriptionsession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addazuresubscriptionsession));
        
        string IMigrationMetadata.Id
        {
            get { return "201503151438290_add-azure-subscription-session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
