// <auto-generated />
namespace WadGraphEs.MetricsEndpoint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sqldatabasesession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sqldatabasesession));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281702325_sql-database-session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
