// <auto-generated />
namespace AzurePlot.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initialschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201503141543398_initial-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
